/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dll */

#ifndef _Included_dll
#define _Included_dll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dll
 * Method:    PIInitialization
 * Signature: (Ljava/lang/String;Ljava/lang/String;DDDZ)I
 */
JNIEXPORT jint JNICALL Java_dll_Initialization
  (JNIEnv *, jobject, jstring, jstring, jdouble, jdouble, jdouble, jboolean);

#ifdef __cplusplus
}
#endif
#endif
